# azure-pipelines-database.yml
trigger:
  branches: { include: [ main ] }
  paths:    { include: [ 'HoneyHub.Platform/Domains/Users/HoneyHub.Users.Database/**', '**/*.sqlproj' ] }
pr: none

pool:
  vmImage: windows-latest

variables:
- group: HoneyHub-Dev
- name: buildConfiguration
  value: Release
- name: sqlprojPath
  value: HoneyHub.Platform/Domains/Users/HoneyHub.Users.Database/HoneyHub.Users.Database.sqlproj
- name: dacpacOutDir
  value: '$(Build.ArtifactStagingDirectory)\dacpac\'

stages:
# ────────────────────────────────────────────────────────────────────────────────
- stage: Build_DACPAC
  displayName: Build DACPAC
  jobs:
  - job: Build
    displayName: Build .sqlproj
    steps:
    - task: VSBuild@1
      displayName: 'Build $(sqlprojPath)'
      inputs:
        solution: '$(sqlprojPath)'
        msbuildArgs: >
          /t:Build
          /p:Configuration=$(buildConfiguration)
          /p:Platform="Any CPU"
          /p:OutDir=$(dacpacOutDir)
        platform: 'Any CPU'
        configuration: '$(buildConfiguration)'
        clean: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish DACPAC artifact'
      inputs:
        targetPath: '$(dacpacOutDir)'
        artifact: 'DatabaseDacpac'

# ────────────────────────────────────────────────────────────────────────────────
- stage: Deploy_DEV
  displayName: Deploy to DEV
  dependsOn: Build_DACPAC
  jobs:
  - deployment: DbDeployDEV
    displayName: 'Azure SQL deploy (DEV)'
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: DatabaseDacpac

          # Built-in DACPAC deploy task (no hardcoded SqlPackage path needed)
          - task: SqlAzureDacpacDeployment@1
            displayName: 'Deploy DACPAC to DEV'
            inputs:
              AuthenticationType: 'connectionString'
              ConnectionString: '$(db-admin-user-connstring)'
              deployType: 'DacpacTask'
              DeploymentAction: 'Publish'
              DacpacFile: '$(Pipeline.Workspace)\DatabaseDacpac\**\*.dacpac'
              AdditionalArguments: >
                /p:BlockOnPossibleDataLoss=true
                /p:DropObjectsNotInSource=false
                /p:AllowIncompatiblePlatform=false
