global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape the OTel Collector's Prometheus exporter endpoint
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]